version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    working_directory: ~/pingcap/docs-cn
    steps:
      - checkout

      - run:
          name: Setup
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            echo 'export NODE_PATH=~/.npm-global/lib/node_modules:$NODE_PATH' >> $BASH_ENV

      - run:
          name: "Check file encoding"
          command: |
            git remote add upstream https://github.com/pingcap/docs-cn.git
            git fetch upstream
            wget https://raw.githubusercontent.com/CharLotteiu/pingcap-docs-checks/main/check-file-encoding.py
            python3 check-file-encoding.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')

      - run:
          name: "Check git conflicts"
          command: |
            wget https://raw.githubusercontent.com/CharLotteiu/pingcap-docs-checks/main/check-conflicts.py
            python3 check-conflicts.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' '*.yml' '*.yaml')

      - run:
          name: "Install markdownlint"
          command: |
            npm install -g markdownlint-cli@0.17.0

      - run:
          name: "Lint edited files"
          command: |
            markdownlint $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')

      - run:
          name: "Check internal links"
          command: |
            scripts/verify-links.sh

      - run:
          name: "Check internal link anchors"
          command: |
            scripts/verify-link-anchors.sh

      - run:
          name: "Check control characters"
          command: |
            wget https://raw.githubusercontent.com/CharLotteiu/pingcap-docs-checks/main/check-control-char.py
            python3 check-control-char.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')

      - run:
          name: "Check unclosed tags"
          command: |
            wget https://raw.githubusercontent.com/CharLotteiu/pingcap-docs-checks/main/check-tags.py
            python3 check-tags.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')

      - run:
          name: "Check manual line breaks"
          command: |
            wget https://raw.githubusercontent.com/CharLotteiu/pingcap-docs-checks/main/check-manual-line-breaks.py
            python3 check-manual-line-breaks.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')

  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/pingcap/docs-cn

    steps:
      - checkout

      - run:
          name: install sdk and awscli
          command: |
            sudo pip3 install boto3
            sudo pip3 install awscli
            printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure


      - run:
          name: "Special Check for Golang User"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py

      - run:
          name: "Generate PDF"
          command: scripts/generate_pdf.sh

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF to Qiniu and S3"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "release-4.0" ]; then
              python3 scripts/upload.py output.pdf tidb-v4.0-zh-manual.pdf;
            fi

      - run:
          name: "Copy Generated PDF"
          command: mkdir /tmp/artifacts && cp output.pdf doc.md /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
<<<<<<< HEAD
=======
#   zhmd:
#     docker:
#       - image: circleci/node:lts
#     working_directory: ~/pingcap/docs-cn
#     steps:
#       - checkout
#       - run:
#           name: Setup
#           command: |
#             mkdir ~/.npm-global
#             npm config set prefix '~/.npm-global'
#             echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
#             echo 'export NODE_PATH=~/.npm-global/lib/node_modules:$NODE_PATH' >> $BASH_ENV
#       - run:
#           name: "Install Zhmd"
#           command: |
#             npm install -g preset-lint-zh
#       - run:
#           name: "zhmd lint"
#           command: |
#             zhmd -c ~/pingcap/docs-cn/.zhlint.yaml

>>>>>>> 3a30845d8 (Temporarilty disable zh.md to avoid jenkins error-reporting (#7104))

workflows:
  version: 2
  lint:
    jobs:
      - lint
<<<<<<< HEAD
=======
#     - zhmd
>>>>>>> 3a30845d8 (Temporarilty disable zh.md to avoid jenkins error-reporting (#7104))
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-4.0
