version: 2

jobs:
  lint:
    docker:
      - image: circleci/ruby:2.4.1-node
    working_directory: ~/pingcap/docs-cn
    steps:
      - checkout

      - run:
          name: "Install markdownlint"
          command: |
            sudo npm install -g markdownlint-cli
            markdownlint --version

      - run:
          name: "Lint README"
          command: markdownlint README.md

      - run:
          name: "Lint dev"
          command: markdownlint dev/

  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/pingcap/docs-cn
    branches:
      only:
        - master
        - website-preview
    steps:
      - checkout

      - run:
          name: "Special Check for Golang User"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py

      - run:
          name: "Generate PDF"
          command: scripts/generate_pdf.sh

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              python3 scripts/upload.py output.pdf tidb-manual-cn.pdf;
            fi
            if [ "${CIRCLE_BRANCH}" == "website-preview" ]; then
              python3 scripts/upload.py output.pdf tidb-manual-cn-preview.pdf;
            fi

      - run:
          name: "Copy Generated PDF"
          command: mkdir /tmp/artifacts && cp output.pdf doc.md /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  lint:
    jobs:
      - lint
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - website-preview
