version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    working_directory: ~/pingcap/docs-cn
    steps:
      - checkout

      - run:
          name: Setup
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            echo 'export NODE_PATH=~/.npm-global/lib/node_modules:$NODE_PATH' >> $BASH_ENV

      - run:
          name: "Check git conflicts"
          command: |
            git remote add upstream https://github.com/pingcap/docs-cn.git
            git fetch upstream
            python3 scripts/check-conflicts.py $(git diff-tree --name-only --no-commit-id -r upstream/master..HEAD -- '*.md' ':(exclude).github/*')

      - run:
          name: "Install markdownlint"
          command: |
            npm install -g markdownlint-cli@0.17.0

      - run:
          name: "Lint edited files"
          command: |
<<<<<<< HEAD
            git remote add upstream https://github.com/pingcap/docs-cn.git
            git fetch upstream
            markdownlint $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')
=======
            markdownlint $(git diff-tree --name-only --no-commit-id -r upstream/master..HEAD -- '*.md' ':(exclude).github/*')
>>>>>>> 90e6a80e... Add conflicts check script and test files (#4696)

      - run:
          name: "Check links"
          command: |
            scripts/verify-links.sh

      - run:
          name: "Check link anchors"
          command: |
            scripts/verify-link-anchors.sh

      - run:
<<<<<<< HEAD
         name: "Check unclosed tags"
         command:
          python3 scripts/check-tags.py $(git diff-tree --name-only --no-commit-id -r upstream/release-4.0..HEAD -- '*.md' ':(exclude).github/*')
=======
          name: "Check unclosed tags"
          command: |
            python3 scripts/check-tags.py $(git diff-tree --name-only --no-commit-id -r upstream/master..HEAD -- '*.md' ':(exclude).github/*')
>>>>>>> 90e6a80e... Add conflicts check script and test files (#4696)

  build:
    docker:
      - image: andelf/doc-build:0.1.9
    working_directory: ~/pingcap/docs-cn

    steps:
      - checkout

      - run:
          name: "Special Check for Golang User"
          command: grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py

      - run:
          name: "Generate PDF"
          command: scripts/generate_pdf.sh

      # echo "222.222.95.49 uc.qbox.me": adds a new host
      - deploy:
          name: "Publish PDF"
          command: |
            sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
            if [ "${CIRCLE_BRANCH}" == "release-4.0" ]; then
              python3 scripts/upload.py output.pdf tidb-stable-zh-manual.pdf;
            fi

      - run:
          name: "Copy Generated PDF"
          command: mkdir /tmp/artifacts && cp output.pdf doc.md /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  lint:
    jobs:
      - lint
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release-4.0
