name: Trigger docs-staging nextgen update

on:
  push:
    paths-ignore:
      - ".github/**"
    branches:
      - feature/preview-top-navigation

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: trigger docs-staging update-nextgen workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DOCS_STAGING }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'pingcap',
              repo: 'docs-staging',
              workflow_id: 'update-nextgen.yml',
              ref: 'nextgen',
              inputs: {
                repo: 'pingcap/docs-cn',
                branch: 'feature/preview-top-navigation'
              }
            })
